//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_ClientesManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bd_pruebaEntities : DbContext
    {
        public bd_pruebaEntities()
            : base("name=bd_pruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
    
        [DbFunction("bd_pruebaEntities", "FTN_CLIENTES_PRUEBA_LISTA_CLIENTES")]
        public virtual IQueryable<FTN_CLIENTES_PRUEBA_LISTA_CLIENTES_Result> FTN_CLIENTES_PRUEBA_LISTA_CLIENTES(string p_BUSQUEDA)
        {
            var p_BUSQUEDAParameter = p_BUSQUEDA != null ?
                new ObjectParameter("P_BUSQUEDA", p_BUSQUEDA) :
                new ObjectParameter("P_BUSQUEDA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FTN_CLIENTES_PRUEBA_LISTA_CLIENTES_Result>("[bd_pruebaEntities].[FTN_CLIENTES_PRUEBA_LISTA_CLIENTES](@P_BUSQUEDA)", p_BUSQUEDAParameter);
        }
    
        public virtual int STPR_CLIENTES_PRUEBA_MANTENIMIENTO(string p_NombreCompleto, Nullable<decimal> p_Identificacion, Nullable<decimal> p_Telefono, Nullable<int> p_ID, string p_Accion, ObjectParameter p_Mensaje)
        {
            var p_NombreCompletoParameter = p_NombreCompleto != null ?
                new ObjectParameter("P_NombreCompleto", p_NombreCompleto) :
                new ObjectParameter("P_NombreCompleto", typeof(string));
    
            var p_IdentificacionParameter = p_Identificacion.HasValue ?
                new ObjectParameter("P_Identificacion", p_Identificacion) :
                new ObjectParameter("P_Identificacion", typeof(decimal));
    
            var p_TelefonoParameter = p_Telefono.HasValue ?
                new ObjectParameter("P_Telefono", p_Telefono) :
                new ObjectParameter("P_Telefono", typeof(decimal));
    
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            var p_AccionParameter = p_Accion != null ?
                new ObjectParameter("P_Accion", p_Accion) :
                new ObjectParameter("P_Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STPR_CLIENTES_PRUEBA_MANTENIMIENTO", p_NombreCompletoParameter, p_IdentificacionParameter, p_TelefonoParameter, p_IDParameter, p_AccionParameter, p_Mensaje);
        }
    }
}
