//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_ClientesManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public long ID { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public int IDENTIFICACION { get; set; }
        public Nullable<int> TELEFONO { get; set; }
    }
}
